name: 📦 Linux Flatpak

on:
  workflow_call:
  workflow_dispatch:

jobs:
  linux-flatpak-build:
    name: "Build"

    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        set-safe-directory: ${{ env.GITHUB_WORKSPACE }}

    # Work around container ownership issue
    - name: Set Safe Directory
      shell: bash
      run: git config --global --add safe.directory "*"

    - name: Build Flatpak
      uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: lindbergh-loader.flatpak
        upload-artifact: false
        manifest-path: scripts/flatpak/com.github.lindberghloader.yml
        build-bundle: true
        verbose: true
        branch: stable
        cache: true
        restore-cache: true
        cache-key: flatpak-${{ hashFiles('scripts/flatpak/*.yaml') }}

    - name: Upload Flatpak
      uses: actions/upload-artifact@v4
      with:
        name: "linux-flatpak"
        path: "lindbergh-loader.flatpak"
