name: Automated Builds

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  workflow_call:
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/*'
      - '.docs/changelog'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/*'
      - '.docs/changelog'

jobs:
  linux-build:
    name: 💻 Linux
    uses: "./.github/workflows/linux-build.yml"
  linux-flatpak:
    name: 📦 Linux Flatpak
    uses: "./.github/workflows/flatpak-build.yml"

  create-release:
    name: 📤 Create Release
    needs: [linux-build, linux-flatpak]
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Display Downloaded Artifacts
        run: find ./artifacts/

      - name: Add 161 to github.run_number
        run: |
          NEW_RUN_NUMBER=$(( ${{ github.run_number }} + 161 ))
          echo "NEW_RUN_NUMBER=$NEW_RUN_NUMBER" >> $GITHUB_ENV

      - name: Create Preview Release
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ env.NEW_RUN_NUMBER }}
          prerelease: false
          title: "Build v${{ env.NEW_RUN_NUMBER }}"
          files: |
            ./artifacts/linux-flatpak/lindbergh-loader.flatpak
            ./artifacts/linux-build/build.tar.gz
